version: '3.8'

services:
  flask:
    build: .
    container_name: minimal-flask
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: minimal-flask-nginx
    ports:
      - "80:80"          # Nginx exposed to host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    restart: always
